projects:
  staffscheduling:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        docsFilePath: src/graphql
        generatedFileName: ''
        maxDepth: 2
extensions:
  amplify:
    version: 3
