projects:
  staffscheduling:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript  # Ensure this is set to 'javascript'
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
